language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t smukes/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true smukes/react-test npm test  

after_success:
  - docker build -t smukes/multi-client ./client
  - docker build -t smukes/multi-nginx ./nginx
  - docker build -t smukes/multi-server ./server
  - docker build -t smukes/multi-worker ./worker

#Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Pushing to docker hub
  - docker push smukes/multi-client
  - docker push smukes/multi-nginx
  - docker push smukes/multi-server
  - docker push smukes/multi-worker
